# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FilterMispickedIons <- function(peakTable, ringWin, isoWin, trWin, maxIsoShift, mergePeaks, mergeMethod) {
    .Call(`_mpactr_FilterMispickedIons`, peakTable, ringWin, isoWin, trWin, maxIsoShift, mergePeaks, mergeMethod)
}

Test <- function(ls) {
    .Call(`_mpactr_Test`, ls)
}

Test1 <- function() {
    .Call(`_mpactr_Test1`)
}

Test2 <- function() {
    .Call(`_mpactr_Test2`)
}

