# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule: [{cron: '0 4 * * 1'}]
  # run every monday at 4 am.

name: lint

permissions: read-all

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      - name: Lint Package
        run: lintr::lint_package(linters = lintr::linters_with_defaults())
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true